// deno-lint-ignore-file no-explicit-any
import type {
  InferSchemaType,
  Model as MongoModel,
  ObtainSchemaGeneric,
  Schema,
  SchemaDefinition,
  SchemaOptions,
} from 'mongoose'
import type { BaseCustomSchema, MongoSchemaDefinition } from './schema.ts'
import type { SchemaStatics } from './statics.ts'
import type { BaseAttributes } from 'database/typings/general.ts'
import type { Model, SchemaMethods } from './commons.ts'

/**
 * Defines the structure of a MongoDB model, including its schema definition, options, and an optional callback
 * function for further schema customization.
 *
 * This type is used to define models in a MongoDB context, providing a schema definition and additional options
 * for the model. It also supports an optional `callback` that can be used to modify or extend the schema after
 * it has been defined.
 *
 * @template Attrs - The attributes (or schema) of the model. Defaults to `any` if not provided.
 *
 * @type MongoModelDefinition
 */
export type MongoModelDefinition<
  Attrs extends BaseAttributes = any,
> = {
  /**
   * The schema definition for the model, specifying the fields
   * and their types, validation, and other constraints.
   */
  definition: MongoSchemaDefinition<Attrs>
  /**
   * Optional additional options to customize the behavior of the model
   * schema, such as validation, timestamps, and indexes.
   */
  options?: SchemaOptions
  /**
   * Optional callback to modify the schema after it has been defined.
   * @param {Schema<MongoSchemaDefinition<Attrs>>} schema - The MongoDB schema to be modified.
   * @returns {Promise<Schema> | Schema} - The modified schema, either synchronously or asynchronously.
   */
  callback?: (schema: Schema<MongoSchemaDefinition<Attrs>>) => Promise<Schema> | Schema
}

/**
 * Represents a model constructed from a given schema type.
 * It combines MongoModel with the inferred schema types and additional static methods.
 *
 * @template S - The schema type extending Schema.
 */
export type ModelBySchema<S extends Schema> =
  & MongoModel<
    InferSchemaType<S>,
    ObtainSchemaGeneric<S, 'TQueryHelpers'>,
    ObtainSchemaGeneric<S, 'TInstanceMethods'> & SchemaMethods,
    ObtainSchemaGeneric<S, 'TVirtuals'>,
    S
  >
  & ObtainSchemaGeneric<S, 'TStaticMethods'>
  & {
    schema:
      & S
      & MongoModel<
        InferSchemaType<S>,
        ObtainSchemaGeneric<S, 'TQueryHelpers'>,
        ObtainSchemaGeneric<S, 'TInstanceMethods'>,
        ObtainSchemaGeneric<S, 'TVirtuals'>,
        S
      >['schema']
  }

/**
 * Represents a generic MongoModel with attributes, options and a schema.
 */
export type AdaptedModel<
  Attrs extends BaseAttributes = any,
  Opts extends SchemaOptions = SchemaOptions,
> = Model<Attrs> & SchemaStatics & {
  schema: SchemaDefinition<Opts> & BaseCustomSchema
  db: never
}

/**
 * Represents a generic MongoModel generated by a schema with attributes.
 */
export type AdaptedModelBySchema<S extends Schema> = ModelBySchema<S> & SchemaStatics & {
  schema: BaseCustomSchema & ModelBySchema<S>['schema']
  db: never
}

/**
 * Connector Model general options
 */
export type GetModelOptions = {
  /**
   * Enables the use of `AsyncLocalStorage` (ALS) for the current model.
   * Once enabled, all model accessors and transformations — such as data access policies —
   * will operate within the active ALS session.
   *
   * ⚠️ Make sure ALS is also activated in the controller or handler injection options when enabled.
   */
  useALS?: boolean
}
